name: Crash MATLAB (expect 3 crashes on Linux and 3 normal errors on Windows)

on:
  # Trigger the workflow on push or pull request
  push:
  #pull_request:  # DANGEROUS! MUST be disabled for self-hosted runners!
  # Trigger the workflow by cron. The default time zone of GitHub Actions is UTC.
  schedule:
    - cron: '0 18 * * *'
  # Trigger the workflow when it is manually triggered
  workflow_dispatch:

jobs:
  test:
    name: Crash MATLAB during MEX setup or mexification
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        crash_type: [default, setup, mex]
        crash_indicator : [true, false]
        exclude:
          - crash_type: default
            crash_indicator: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1.1.0

      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: |
              if strcmpi('${{ matrix.crash_type }}', 'default')
                  if ${{ matrix.crash_indicator }}
                      crash;
                  end
              else
                  if ${{ matrix.crash_indicator }}
                      crash('${{ matrix.crash_type }}')
                  else
                      crash('${{ matrix.crash_type }}', false)
                  end
              end
